// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJUOv86sMxgWNKgQ0ZESgaQ1zjmxqSX8',
    appId: '1:838228543665:web:9dbf9f7764d9c2d3e93a90',
    messagingSenderId: '838228543665',
    projectId: 'chatting-app-265da',
    authDomain: 'chatting-app-265da.firebaseapp.com',
    storageBucket: 'chatting-app-265da.appspot.com',
    measurementId: 'G-W7K9XF99S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBpsAUMKMGoTblrUdfu3XO2qPYouk2er8',
    appId: '1:838228543665:android:acbe52bb76e39f73e93a90',
    messagingSenderId: '838228543665',
    projectId: 'chatting-app-265da',
    storageBucket: 'chatting-app-265da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwJC4xDg9l3ZDYTX47uULMAnKHW9IaQg',
    appId: '1:838228543665:ios:2ae6c6d0337ee29ae93a90',
    messagingSenderId: '838228543665',
    projectId: 'chatting-app-265da',
    storageBucket: 'chatting-app-265da.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwJC4xDg9l3ZDYTX47uULMAnKHW9IaQg',
    appId: '1:838228543665:ios:5e1af21400fbb023e93a90',
    messagingSenderId: '838228543665',
    projectId: 'chatting-app-265da',
    storageBucket: 'chatting-app-265da.appspot.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
